name: docker-image-frontend

on: 
  # release:
  #   types: [published]
  push:
    paths: 
      - 'platform/**'
  #   tags:
  #     - 'v*'
  #   branches: 
  #     - master
  # schedule:
  #   - cron: 0 8 * * 5
  # watch:
  #   types: [started]
  workflow_dispatch:

env:
  IMAGE_NAME: cloudgrin/frontend-lowcode-platform

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./platform
          file: ./platform/Dockerfile.prod
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
